# Site settings
title: NGForever BLOG
header-img: img/home-bg.jpg
email: 798618048@qq.com
description: "欢迎访问我的博客^-^"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhangzinan.github.io"
#twitter_username: zhangzinan
#facebook_username:  zhangzinan
github_username:  zhangzinan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]